spring:
  cloud:
    config:      
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

common:
  sample_key: common_sample_key_git_value
cookie:
  domain: commmmmmmmmmon